import type { FormConfig } from './form-types';

export const FORM_CONFIGS: FormConfig[] = [
  {
    type: 'kom',
    title: 'Pendaftaran KOM',
    description: 'Daftar kelas Kehidupan Orientasi Melayani',
    icon: 'GraduationCap',
    externalUrl: 'https://bit.ly/DaftarKOMBarsiBEC',
    sections: [
      { title: 'Data Pribadi', fields: ['namaLengkap', 'tempatLahir', 'tanggalLahir', 'jenisKelamin', 'alamat'] },
      { title: 'Kontak', fields: ['noTelepon', 'email'] },
      { title: 'Informasi KOM', fields: ['levelKOM', 'sudahBaptis', 'gerejaAsal'] },
    ],
    steps: [
      { field: 'namaLengkap', question: 'Siapa nama lengkap Anda?', label: 'Nama lengkap', type: 'text', placeholder: 'cth. Budi Santoso' },
      { field: 'tempatLahir', question: 'Dimana tempat lahir Anda?', label: 'Tempat lahir', type: 'text', placeholder: 'cth. Bandung', half: true },
      { field: 'tanggalLahir', question: 'Kapan tanggal lahir Anda?', label: 'Tanggal lahir', type: 'date', half: true },
      { field: 'jenisKelamin', question: 'Jenis kelamin?', label: 'Jenis kelamin', type: 'select', options: ['Pria', 'Wanita'] },
      { field: 'alamat', question: 'Alamat tempat tinggal saat ini?', label: 'Alamat', type: 'textarea', placeholder: 'Alamat lengkap' },
      { field: 'noTelepon', question: 'Nomor WhatsApp Anda?', label: 'Nomor WhatsApp', type: 'tel', placeholder: '08xx xxxx xxxx', half: true },
      { field: 'email', question: 'Alamat email? (opsional)', label: 'Email', type: 'email', optional: true, placeholder: 'nama@email.com', half: true },
      { field: 'levelKOM', question: 'Level KOM yang ingin diikuti?', label: 'Level KOM', type: 'select', options: ['100', '200', '300', '400'] },
      { field: 'sudahBaptis', question: 'Apakah sudah dibaptis?', label: 'Sudah dibaptis', type: 'select', options: ['Sudah', 'Belum'], half: true },
      { field: 'gerejaAsal', question: 'Gereja asal? (kosongkan jika dari BEC)', label: 'Gereja asal', type: 'text', optional: true, placeholder: 'Kosongkan jika dari BEC', half: true },
    ],
  },
  {
    type: 'baptism',
    title: 'Pendaftaran Baptisan',
    description: 'Daftar baptisan air',
    icon: 'Droplets',
    sections: [
      { title: 'Data Pribadi', fields: ['namaLengkap', 'nomorKTP', 'tempatLahir', 'tanggalLahir', 'jenisKelamin'] },
      { title: 'Alamat', fields: ['alamat', 'rtRw', 'kota', 'kecamatan', 'kelurahan', 'kodePos'] },
      { title: 'Kontak', fields: ['noTelepon', 'email'] },
      { title: 'Keluarga', fields: ['namaAyah', 'namaIbu'] },
      { title: 'Informasi Baptisan', fields: ['tanggalBaptis', 'sudahKOM100', 'sudahKAJ', 'alasanBaptis'] },
    ],
    steps: [
      { field: 'namaLengkap', question: 'Siapa nama lengkap Anda?', label: 'Nama lengkap', type: 'text', placeholder: 'cth. Budi Santoso' },
      { field: 'nomorKTP', question: 'Berapa nomor KTP (NIK) Anda?', label: 'Nomor KTP (NIK)', type: 'text', placeholder: '16 digit NIK' },
      { field: 'tempatLahir', question: 'Dimana tempat lahir Anda?', label: 'Tempat lahir', type: 'text', placeholder: 'cth. Bandung', half: true },
      { field: 'tanggalLahir', question: 'Kapan tanggal lahir Anda?', label: 'Tanggal lahir', type: 'date', half: true },
      { field: 'jenisKelamin', question: 'Jenis kelamin?', label: 'Jenis kelamin', type: 'select', options: ['Pria', 'Wanita'] },
      { field: 'alamat', question: 'Alamat tempat tinggal saat ini?', label: 'Alamat', type: 'textarea', placeholder: 'Alamat lengkap (nama jalan & nomor)' },
      { field: 'rtRw', question: 'RT/RW?', label: 'RT/RW', type: 'text', placeholder: 'cth. 01/07', half: true },
      { field: 'provinsi', question: 'Provinsi?', label: 'Provinsi', type: 'select', chainType: 'province', hidden: true, defaultValue: 'Jawa Barat' },
      { field: 'kota', question: 'Kota/Kabupaten?', label: 'Kota/Kabupaten', type: 'select', chainType: 'regency', chainParent: 'provinsi', half: true },
      { field: 'kecamatan', question: 'Kecamatan?', label: 'Kecamatan', type: 'select', chainType: 'district', chainParent: 'kota', half: true },
      { field: 'kelurahan', question: 'Kelurahan?', label: 'Kelurahan', type: 'select', chainType: 'village', chainParent: 'kecamatan', half: true },
      { field: 'kodePos', question: 'Kode pos?', label: 'Kode Pos', type: 'text', placeholder: 'cth. 40123', half: true },
      { field: 'noTelepon', question: 'Nomor WhatsApp Anda?', label: 'Nomor WhatsApp', type: 'tel', placeholder: '08xx xxxx xxxx', half: true },
      { field: 'email', question: 'Alamat email?', label: 'Email', type: 'email', placeholder: 'nama@email.com', half: true },
      { field: 'namaAyah', question: 'Siapa nama ayah Anda?', label: 'Nama Ayah', type: 'text', placeholder: 'Nama lengkap ayah', half: true },
      { field: 'namaIbu', question: 'Siapa nama ibu Anda?', label: 'Nama Ibu', type: 'text', placeholder: 'Nama lengkap ibu', half: true },
      { field: 'tanggalBaptis', question: 'Pilih tanggal baptisan yang tersedia:', label: 'Tanggal baptisan', type: 'select', dynamicOptionsUrl: '/api/forms/dates?type=baptism' },
      { field: 'sudahKOM100', question: 'Apakah sudah menyelesaikan KOM 100?', label: 'Sudah KOM 100', type: 'select', options: ['Sudah', 'Belum'], half: true },
      { field: 'sudahKAJ', question: 'Apakah Anda sudah memiliki KAJ?', label: 'Memiliki KAJ', type: 'select', options: ['Sudah', 'Belum'], half: true },
      { field: 'alasanBaptis', question: 'Ceritakan alasan dan kesaksian Anda untuk dibaptis.', label: 'Alasan & kesaksian', type: 'textarea', placeholder: 'Ceritakan alasan dan kesaksian Anda' },
    ],
  },
  {
    type: 'child-dedication',
    title: 'Penyerahan Anak',
    description: 'Daftar penyerahan anak',
    icon: 'Baby',
    sections: [
      { title: 'Data Anak', fields: ['namaAnak', 'namaPanggilan', 'jenisKelaminAnak', 'tempatLahirAnak', 'tanggalLahirAnak'] },
      { title: 'Alamat', fields: ['alamat', 'rtRw', 'kota', 'kecamatan', 'kelurahan', 'kodePos', 'noTelepon'] },
      { title: 'Data Orang Tua', fields: ['cabangIbadah', 'namaAyah', 'namaIbu'] },
      { title: 'Informasi Penyerahan', fields: ['tanggalPenyerahan', 'penyerahanDilakukanOleh'] },
    ],
    steps: [
      { field: 'namaAnak', question: 'Siapa nama lengkap anak?', label: 'Nama lengkap anak', type: 'text', placeholder: 'cth. Sarah Putri' },
      { field: 'namaPanggilan', question: 'Nama panggilan anak?', label: 'Nama panggilan', type: 'text', placeholder: 'cth. Sarah', half: true },
      { field: 'jenisKelaminAnak', question: 'Jenis kelamin anak?', label: 'Jenis kelamin', type: 'select', options: ['Laki-laki', 'Perempuan'], half: true },
      { field: 'tempatLahirAnak', question: 'Dimana tempat lahir anak?', label: 'Tempat lahir', type: 'text', placeholder: 'cth. Bandung', half: true },
      { field: 'tanggalLahirAnak', question: 'Kapan tanggal lahir anak?', label: 'Tanggal lahir', type: 'date', half: true },
      { field: 'alamat', question: 'Alamat tempat tinggal keluarga?', label: 'Alamat', type: 'textarea', placeholder: 'Nama jalan & nomor rumah' },
      { field: 'rtRw', question: 'RT/RW?', label: 'RT/RW', type: 'text', placeholder: 'cth. 01/07', half: true },
      { field: 'provinsi', question: 'Provinsi?', label: 'Provinsi', type: 'select', chainType: 'province', hidden: true, defaultValue: 'Jawa Barat' },
      { field: 'kota', question: 'Kota/Kabupaten?', label: 'Kota/Kabupaten', type: 'select', chainType: 'regency', chainParent: 'provinsi', half: true },
      { field: 'kecamatan', question: 'Kecamatan?', label: 'Kecamatan', type: 'select', chainType: 'district', chainParent: 'kota', half: true },
      { field: 'kelurahan', question: 'Kelurahan?', label: 'Kelurahan', type: 'select', chainType: 'village', chainParent: 'kecamatan', half: true },
      { field: 'kodePos', question: 'Kode pos?', label: 'Kode Pos', type: 'text', placeholder: 'cth. 40112', half: true },
      { field: 'noTelepon', question: 'Nomor HP orang tua?', label: 'No. HP', type: 'tel', placeholder: '08xx xxxx xxxx', half: true },
      { field: 'cabangIbadah', question: 'Cabang ibadah yang diikuti?', label: 'Cabang ibadah', type: 'text', placeholder: 'cth. BEC Sukawarna' },
      { field: 'namaAyah', question: 'Nama lengkap ayah?', label: 'Nama ayah', type: 'text', placeholder: 'Nama lengkap ayah', half: true },
      { field: 'namaIbu', question: 'Nama lengkap ibu?', label: 'Nama ibu', type: 'text', placeholder: 'Nama lengkap ibu', half: true },
      { field: 'tanggalPenyerahan', question: 'Kapan rencana tanggal penyerahan anak?', label: 'Tanggal penyerahan', type: 'date', half: true },
      { field: 'penyerahanDilakukanOleh', question: 'Penyerahan akan dilakukan oleh siapa? (nama pendeta/hamba Tuhan)', label: 'Dilakukan oleh', type: 'text', placeholder: 'cth. Pdm. Budi', half: true },
    ],
  },
  {
    type: 'prayer',
    title: 'Pokok Doa',
    description: 'Sampaikan pokok doa Anda',
    icon: 'HandHeart',
    steps: [
      { field: 'namaLengkap', question: 'Siapa nama Anda?', label: 'Nama', type: 'text', placeholder: 'cth. Budi Santoso', half: true },
      { field: 'noTelepon', question: 'Nomor WhatsApp Anda?', label: 'Nomor WhatsApp', type: 'tel', placeholder: '08xx xxxx xxxx', half: true },
      { field: 'kategoriDoa', question: 'Kategori pokok doa?', label: 'Kategori', type: 'select', options: ['Kesehatan', 'Keluarga', 'Pekerjaan', 'Rohani', 'Lainnya'] },
      { field: 'isiDoa', question: 'Tuliskan pokok doa Anda.', label: 'Pokok doa', type: 'textarea', placeholder: 'Tuliskan pokok doa Anda' },
      { field: 'bolehDibagikan', question: 'Bolehkah pokok doa ini dibagikan ke tim pendoa?', label: 'Boleh dibagikan ke tim pendoa', type: 'select', options: ['Boleh', 'Tidak'] },
    ],
  },
  {
    type: 'mclass',
    title: 'Pendaftaran M-Class',
    description: 'Daftar kelas Membership',
    icon: 'BookOpen',
    steps: [
      { field: 'noMClass', question: '', label: 'No. M-Class', type: 'text', hidden: true },
      { field: 'namaLengkap', question: 'Siapa nama lengkap Anda?', label: 'Nama lengkap', type: 'text', placeholder: 'cth. Budi Santoso' },
      { field: 'noTelepon', question: 'Nomor WhatsApp Anda?', label: 'Nomor WhatsApp', type: 'tel', placeholder: '08xx xxxx xxxx' },
      { field: 'tanggalMClass', question: 'Pilih tanggal M-Class yang tersedia:', label: 'Tanggal M-Class', type: 'select', dynamicOptionsUrl: '/api/forms/dates?type=mclass&months=2' },
    ],
  },
];

export function getFormConfig(type: string): FormConfig | undefined {
  return FORM_CONFIGS.find(c => c.type === type);
}

export const FORM_TYPE_LABELS: Record<string, string> = {
  kom: 'KOM',
  baptism: 'Baptisan',
  'child-dedication': 'Penyerahan Anak',
  prayer: 'Pokok Doa',
  mclass: 'M-Class',
};

export const FORM_STATUS_LABELS: Record<string, string> = {
  pending: 'Menunggu',
  reviewed: 'Ditinjau',
  completed: 'Selesai',
  hadir: 'Hadir',
  'tidak-hadir': 'Tidak Hadir',
};
