import type { Firestore } from 'firebase-admin/firestore';
import { generateUniqueSlug } from '@/lib/slug';
import { formatIndoDate } from '@/lib/notetaker';

/**
 * Turn a sermon capture into a kabar post.
 *
 * Extracted from /api/sermon-captures/[id]/to-kabar so the automated publish
 * chain creates the exact same document the manual button does — the only
 * difference between them is the `publish` flag.
 */

export interface CreateKabarResult {
  id: string;
  slug: string;
  title: string;
  published: boolean;
  alreadyExisted: boolean;
}

export interface CreateKabarOptions {
  /** When true the post goes live immediately. Callers must revalidate after. */
  publish?: boolean;
}

/**
 * Idempotent: if a kabar was already created for this capture, it is returned
 * untouched — EXCEPT that `publish: true` will publish an existing draft, which
 * is what makes the auto-chain safe to retry.
 */
export async function createKabarFromCapture(
  db: Firestore,
  captureId: string,
  options: CreateKabarOptions = {},
): Promise<CreateKabarResult | { error: string }> {
  const captureRef = db.collection('sermon_captures').doc(captureId);
  const captureSnap = await captureRef.get();
  if (!captureSnap.exists) return { error: 'Capture not found' };

  const cap = captureSnap.data()!;
  const publish = options.publish === true;

  // Idempotency: reuse the existing draft rather than creating a duplicate.
  if (cap.kabarId) {
    const existing = await db.collection('updates').doc(cap.kabarId).get();
    if (existing.exists) {
      const data = existing.data()!;
      if (publish && data.published !== true) {
        await existing.ref.update({ published: true, updatedAt: new Date().toISOString() });
      }
      return {
        id: existing.id,
        slug: data.slug,
        title: data.title,
        published: publish ? true : data.published === true,
        alreadyExisted: true,
      };
    }
  }

  const sermonDateLabel = formatIndoDate(cap.sermonDate ?? new Date().toISOString().slice(0, 10));
  const serviceSuffix = cap.serviceNumber ? ` (Ibadah Raya ${cap.serviceNumber})` : '';
  const title = `Catatan Khotbah - Ibadah Raya - ${sermonDateLabel}${serviceSuffix}`;
  const slug = await generateUniqueSlug(title, db);

  // Priority: combined (merged AI+notetaker) > final (AI only) > latest (legacy)
  const sourceSummary: string = cap.combinedSummary || cap.finalSummary || cap.latestSummary || '';
  const isCombined = Boolean(cap.combinedSummary);
  const content = summaryToTipTapHtml(sourceSummary, isCombined, cap.summarySnapshots ?? []);
  const excerptText = firstSentenceOf(sourceSummary).slice(0, 145);
  const excerpt = excerptText
    ? `<p>${escapeHtml(excerptText)}…</p>`
    : `<p>Catatan khotbah ${sermonDateLabel}${serviceSuffix}.</p>`;

  const now = new Date().toISOString();
  const doc = {
    title,
    slug,
    excerpt,
    content,
    category: 'Ibadah',
    date: cap.sermonDate ?? new Date().toISOString().slice(0, 10),
    color: 'oklch(0.35 0.04 175)',
    imageUrl: cap.videoId ? `https://i.ytimg.com/vi/${cap.videoId}/maxresdefault.jpg` : null,
    isVideo: false,
    pinned: false,
    published: publish,
    isAutoGenerated: true,
    sourceCaptureId: captureId,
    youtubeVideoId: cap.videoId ?? null,
    createdAt: now,
    updatedAt: now,
  };

  const ref = await db.collection('updates').add(doc);
  // Link back so future re-imports are idempotent
  await captureRef.update({ kabarId: ref.id, kabarSlug: slug });

  return { id: ref.id, slug, title, published: publish, alreadyExisted: false };
}

// ─── helpers ────────────────────────────────────────────────────────

export function firstSentenceOf(s: string): string {
  const cleaned = s.replace(/^[#*\-\s]+/, '').replace(/\n+/g, ' ').trim();
  const m = cleaned.match(/^([^.!?]+[.!?])/);
  return (m ? m[1] : cleaned).trim();
}

export function escapeHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

/**
 * Turn the summary (markdown-ish bullets) into TipTap HTML.
 *
 * The leading disclaimer differs by provenance: a COMBINED note was cross-checked
 * by a human notulen who was in the room, so it does not carry the same
 * "review before publishing" caveat an unattended AI-only summary does.
 */
export function summaryToTipTapHtml(
  latest: string,
  isCombined: boolean,
  snapshots: Array<{ atSec: number; summary: string; transcriptChars: number }>,
): string {
  const parts: string[] = [];
  parts.push(
    isCombined
      ? '<p><em>Catatan khotbah hasil gabungan catatan notulen ibadah dan transkrip live.</em></p>'
      : '<p><em>Ringkasan otomatis dari live transcription (Gemini 3.1 + Gemini 2.5 Pro). Silakan tinjau dan edit sebelum publikasi.</em></p>',
  );

  parts.push(bulletsBlockToHtml(latest));

  // Timeline is noise on a polished combined note — only useful for raw AI output.
  if (!isCombined && snapshots.length > 1) {
    parts.push('<p><strong>Timeline ringkasan (per menit):</strong></p>');
    snapshots.forEach((s) => {
      const mm = String(Math.floor(s.atSec / 60)).padStart(2, '0');
      const ss = String(s.atSec % 60).padStart(2, '0');
      parts.push(`<p><em>[${mm}:${ss}]</em></p>`);
      parts.push(bulletsBlockToHtml(s.summary));
    });
  }
  parts.push('<p><strong>Tuhan Yesus memberkati</strong></p>');
  return parts.join('');
}

export function bulletsBlockToHtml(text: string): string {
  const lines = text.split('\n').map((l) => l.trim()).filter(Boolean);
  const bullets: string[] = [];
  for (const line of lines) {
    const m = line.match(/^[*\-•]\s+(.+)$/);
    if (m) bullets.push(m[1]);
    else if (bullets.length && !line.match(/^[#`]/)) {
      // Continuation of previous bullet
      bullets[bullets.length - 1] += ' ' + line;
    }
  }
  if (bullets.length) {
    return '<ul>' + bullets.map((b) => `<li><p>${escapeHtml(stripMd(b))}</p></li>`).join('') + '</ul>';
  }
  // Fallback: plain paragraphs
  return lines.map((l) => `<p>${escapeHtml(stripMd(l))}</p>`).join('');
}

export function stripMd(s: string): string {
  return s.replace(/\*\*([^*]+)\*\*/g, '$1').replace(/\*([^*]+)\*/g, '$1');
}
