import { NextRequest, NextResponse } from 'next/server';
import { revalidatePath } from 'next/cache';
import { getAdminFirestore, verifyAuthToken } from '@/lib/firebase-admin';
import { generateUniqueSlug } from '@/lib/slug';
import { logAdminAction } from '@/lib/admin-logger';

// POST /api/sermon-captures/[id]/to-kabar
// Convert a sermon capture into a kabar draft (unpublished). Idempotent: if a draft
// was already created for this capture, returns it instead of creating a duplicate.
export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  const authError = await verifyAuthToken(request);
  if (authError) return authError;

  const { id } = await params;
  try {
    const db = getAdminFirestore();
    const captureRef = db.collection('sermon_captures').doc(id);
    const captureSnap = await captureRef.get();
    if (!captureSnap.exists) return NextResponse.json({ error: 'Capture not found' }, { status: 404 });

    const cap = captureSnap.data()!;

    // Idempotency: if kabarId already set and that doc exists, return it
    if (cap.kabarId) {
      const existing = await db.collection('updates').doc(cap.kabarId).get();
      if (existing.exists) {
        return NextResponse.json({
          id: existing.id,
          ...existing.data(),
          alreadyExisted: true,
        });
      }
    }

    const sermonDateLabel = formatIndoDate(cap.sermonDate ?? new Date().toISOString().slice(0, 10));
    const serviceLabel = cap.serviceNumber ? ` (Ibadah Raya ${cap.serviceNumber})` : '';
    const title = `Catatan Khotbah - Ibadah Raya - ${sermonDateLabel}${serviceLabel}`;
    const slug = await generateUniqueSlug(title, db);

    const content = summaryToTipTapHtml(cap.latestSummary ?? '', cap.summarySnapshots ?? []);
    const excerptText = firstSentenceOf(cap.latestSummary ?? '').slice(0, 145);
    const excerpt = excerptText ? `<p>${escapeHtml(excerptText)}…</p>` : `<p>Catatan khotbah ${sermonDateLabel}${serviceLabel}.</p>`;

    const now = new Date().toISOString();
    const doc = {
      title,
      slug,
      excerpt,
      content,
      category: 'Ibadah',
      date: cap.sermonDate ?? new Date().toISOString().slice(0, 10),
      color: 'oklch(0.35 0.04 175)',
      imageUrl: cap.videoId ? `https://i.ytimg.com/vi/${cap.videoId}/maxresdefault.jpg` : null,
      isVideo: false,
      pinned: false,
      published: false,
      isAutoGenerated: true,
      sourceCaptureId: id,
      youtubeVideoId: cap.videoId ?? null,
      createdAt: now,
      updatedAt: now,
    };

    const ref = await db.collection('updates').add(doc);
    // Link back so future re-imports are idempotent
    await captureRef.update({ kabarId: ref.id, kabarSlug: slug });
    logAdminAction(request, 'create', 'kabar', { resourceId: ref.id, resourceTitle: title });
    revalidatePath('/kabar');
    revalidatePath('/sitemap.xml');

    return NextResponse.json({ id: ref.id, ...doc, alreadyExisted: false }, { status: 201 });
  } catch (err) {
    console.error('to-kabar error:', err);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

// ─── helpers ────────────────────────────────────────────────────────

const INDO_MONTHS = ['Januari','Februari','Maret','April','Mei','Juni','Juli','Agustus','September','Oktober','November','Desember'];
function formatIndoDate(iso: string): string {
  const [y, m, d] = iso.split('-');
  return `${parseInt(d, 10)} ${INDO_MONTHS[parseInt(m, 10) - 1]} ${y}`;
}

function firstSentenceOf(s: string): string {
  const cleaned = s.replace(/^[#*\-\s]+/, '').replace(/\n+/g, ' ').trim();
  const m = cleaned.match(/^([^.!?]+[.!?])/);
  return (m ? m[1] : cleaned).trim();
}

function escapeHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

// Turn the ASI1 summary (markdown-ish bullets) into TipTap HTML.
// Falls back gracefully when format isn't bullets.
function summaryToTipTapHtml(latest: string, snapshots: Array<{ atSec: number; summary: string; transcriptChars: number }>): string {
  const parts: string[] = [];
  parts.push('<p><em>Ringkasan otomatis dari live transcription (Gemini 3.1 + ASI1 Mini). Silakan tinjau dan edit sebelum publikasi.</em></p>');

  // Use the latest snapshot as the headline summary
  parts.push(bulletsBlockToHtml(latest));

  // Optionally include a "timeline" section if multiple snapshots exist (>1)
  if (snapshots.length > 1) {
    parts.push('<p><strong>Timeline ringkasan (per menit):</strong></p>');
    snapshots.forEach((s) => {
      const mm = String(Math.floor(s.atSec / 60)).padStart(2, '0');
      const ss = String(s.atSec % 60).padStart(2, '0');
      parts.push(`<p><em>[${mm}:${ss}]</em></p>`);
      parts.push(bulletsBlockToHtml(s.summary));
    });
  }
  parts.push('<p><strong>Tuhan Yesus memberkati</strong></p>');
  return parts.join('');
}

function bulletsBlockToHtml(text: string): string {
  const lines = text.split('\n').map((l) => l.trim()).filter(Boolean);
  const bullets: string[] = [];
  for (const line of lines) {
    const m = line.match(/^[\*\-•]\s+(.+)$/);
    if (m) bullets.push(m[1]);
    else if (bullets.length && !line.match(/^[#`]/)) {
      // Continuation of previous bullet
      bullets[bullets.length - 1] += ' ' + line;
    }
  }
  if (bullets.length) {
    return '<ul>' + bullets.map((b) => `<li><p>${escapeHtml(stripMd(b))}</p></li>`).join('') + '</ul>';
  }
  // Fallback: plain paragraphs
  return lines.map((l) => `<p>${escapeHtml(stripMd(l))}</p>`).join('');
}

function stripMd(s: string): string {
  return s.replace(/\*\*([^*]+)\*\*/g, '$1').replace(/\*([^*]+)\*/g, '$1');
}
